### PR TITLE
ROR-Group-Project: Final Milestone

### PR DESCRIPTION
**Pull request by SaidRasinlic**
**P.S:** _I'm the last student in the current module 5 so I've been alone whole week. Microverse offered me two things to work solo or wait for another cohort until they come to this module, I choosed to work solo. As a proof here is the image of Microverse student success team. Please click this link:_

[E-Mail from Microverse](https://drive.google.com/file/d/1mxxmJDw_nRkeRh3PW0mXiiuGnZPSK2JS/view?usp=sharing)

### In this milestone I've finalized all the requirements including:

- A login page.
- A registration page.
- A food list (with all CRUD implementation, except for 'update').
- A recipes list (with all CRUD implementation, except for 'update').
- A general shopping list view (all missing food for all your recipes and total price).
- A list of all public recipes from other users with their names and total prices.

### CODE REVIEW

**Review by danielufeli — APPROVED** [review]
Hi @SaidRasinlic , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 

You have submitted a project, that only you worked on, this is a Group Project and it is required that you work on it as a group  [You can get more information here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/code_review_flow_group_projects.md) 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by SaidRasinlic** [comment]
> Hi @SaidRasinlic ,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that only you worked on, this is a Group Project and it is required that you work on it as a group [You can get more information here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/code_review_flow_group_projects.md)
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

I have mentioned in my PR that I am the only one in this cohort which means I'm the last student from my cohort in current module 5. Microverse gave me a chance to choose if I will work solo or wait 14 days until another group comes. I choosed working solo. Here is the link of the email conversation [E-Mail from Microverse](https://drive.google.com/file/d/1mxxmJDw_nRkeRh3PW0mXiiuGnZPSK2JS/view?usp=sharing)

**Comment by danielufeli** [comment]
ok, @SaidRasinlic kindly re-submit.

**Review by AshakaE — APPROVED** [review]
Hi @SaidRasinlic & @danielufeli  🙋 ,

Kindly remember to remove comments from your code 👍  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
